//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class product
    {
        public int Id { get; set; }
        [DisplayName("Product Name")]
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        [DisplayName("Category Name")]
        public Nullable<int> CID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual category category { get; set; }
    }
}
